version: '3.6'
services:
  influxdb:
    container_name: influxdb
    image: "influxdb:1.8"
    restart: unless-stopped
    ports:
      - "8086:8086"
      - "8083:8083"
      - "2003:2003"
    env_file:
      - ./services/influxdb/influxdb.env
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb
      - ./backups/influxdb/db:/var/lib/influxdb/backup
      - /etc/letsencrypt/live/<domain>/fullchain.pem:/etc/ssl/fullchain.pem
      - /etc/letsencrypt/live/<domain>/privkey.pem:/etc/ssl/privkey.pem

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    user: "0"
    ports:
      - "3000:3000"
    env_file:
      - ./services/grafana/grafana.env
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./volumes/grafana/log:/var/log/grafana
      - /etc/letsencrypt/live/<domain>/fullchain.pem:/etc/fullchain.pem
      - /etc/letsencrypt/live/<domain>/privkey.pem:/etc/privkey.pem
